<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'ExpressionEngine\\Dependency\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'ExpressionEngine\\Dependency\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'ExpressionEngine\\Dependency\\League\\MimeTypeDetection\\' => array($vendorDir . '/league/mime-type-detection/src'),
    'ExpressionEngine\\Dependency\\League\\Flysystem\\AwsS3v3\\' => array($vendorDir . '/league/flysystem-aws-s3-v3/src'),
    'ExpressionEngine\\Dependency\\League\\Flysystem\\' => array($vendorDir . '/league/flysystem/src'),
    'ExpressionEngine\\Dependency\\JmesPath\\' => array($vendorDir . '/mtdowling/jmespath.php/src'),
    'ExpressionEngine\\Dependency\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'ExpressionEngine\\Dependency\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'ExpressionEngine\\Dependency\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'ExpressionEngine\\Dependency\\Aws\\' => array($vendorDir . '/aws/aws-sdk-php/src'),
);
