name: Package

on:
  push:
    branches: 
      - main

jobs:

    package:
        name: Package Add-on

        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              path: 'cloud_files'

          - name: Remove tests
            working-directory: cloud_files
            run: rm -rf tests

          - name: Archive Addon
            uses: actions/upload-artifact@v2
            with:
              name: cloud_files
              path: cloud_files
