name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
    release:
        name: Release Add-on

        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              path: 'cloud_files'

          - uses: olegtarasov/get-tag@v2.1
            id: tagName

          - name: Update version
            uses: jacobtomlinson/gha-find-replace@v2
            with:
              find: '\d+.\d+.\d+'
              replace: ${{ steps.tagName.outputs.tag }}
              include: "cloud_files/addon.setup.php"
              regex: true

          - name: Remove development files
            working-directory: cloud_files
            run: |
              rm -rf tests
              rm -rf .github

          - name: Archive Add-on
            uses: actions/upload-artifact@v2
            with:
              name: cloud_files
              path: cloud_files
          
          - name: Compress Add-on
            run: zip -r cloud_files.zip cloud_files/

          - uses: ncipollo/release-action@v1.10.0
            with:
              artifacts: "cloud_files.zip"
              allowUpdates: true
              body: Cloud Files ${{ steps.tagName.outputs.tag }}

          - name: Directory Listing on Failure
            if: failure()
            run: |
              ls -latr
              ls -latr cloud_files
